'use client'

import React, { useEffect, useState } from 'react'
import { CloudPulseAPI, AnalyticsSummary } from '@/lib/api'
import { SavingsChart } from '@/components/savings-chart'
import { TrendingUp, DollarSign, Leaf, Award } from 'lucide-react'
import { formatCurrency, formatCarbon } from '@/lib/utils'

export default function AnalyticsPage() {
  const [analytics, setAnalytics] = useState<AnalyticsSummary | null>(null)
  const [loading, setLoading] = useState(true)

  const loadAnalytics = async () => {
    try {
      const data = await CloudPulseAPI.getAnalyticsSummary()
      setAnalytics(data)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadAnalytics()
  }, [])

  if (!analytics) return null

  return (
    <div className="space-y-8">
      <div className="border-b border-border/80 pb-5">
        <h1 className="text-2xl font-bold text-white flex items-center space-x-2">
          <TrendingUp className="w-6 h-6 text-emerald-400" />
          <span>Financial Savings & Carbon Offsetting Engine</span>
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          Detailed breakdown of financial savings generated by rolling metric idle evaluation & estimated CO₂ emissions offset.
        </p>
      </div>

      {/* Summary Highlights */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div className="p-6 rounded-2xl border border-emerald-500/30 bg-emerald-500/5 backdrop-blur-md">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-slate-400 uppercase">Accumulated Financial Savings</span>
            <DollarSign className="w-5 h-5 text-emerald-400" />
          </div>
          <p className="text-3xl font-extrabold text-white mt-2">{formatCurrency(analytics.total_money_saved_usd)}</p>
          <p className="text-xs text-emerald-400 mt-1">Calculated via AWS Price List & On-Demand rates</p>
        </div>

        <div className="p-6 rounded-2xl border border-violet-500/30 bg-violet-500/5 backdrop-blur-md">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-slate-400 uppercase">Carbon Footprint Avoided</span>
            <Leaf className="w-5 h-5 text-violet-400" />
          </div>
          <p className="text-3xl font-extrabold text-white mt-2">{formatCarbon(analytics.total_carbon_saved_kg)}</p>
          <p className="text-xs text-violet-400 mt-1">Based on 0.2 kW server power & grid carbon factor</p>
        </div>

        <div className="p-6 rounded-2xl border border-cyan-500/30 bg-cyan-500/5 backdrop-blur-md">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-slate-400 uppercase">Engine Efficiency Score</span>
            <Award className="w-5 h-5 text-cyan-400" />
          </div>
          <p className="text-3xl font-extrabold text-white mt-2">94.8%</p>
          <p className="text-xs text-cyan-400 mt-1">Idle Detection Precision & Zero False Stops</p>
        </div>
      </div>

      <SavingsChart analytics={analytics} />
    </div>
  )
}
